# adding this file to ensure we are ignoring it

openapi: 3.0.1
info:
  title: Your API
  version: 1.0.0
paths:
  /example:
    get:
      summary: Example endpoint
      responses:
        '200':
          description: OK
components:
  schemas:
    Example:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
  properties:
    broken:
      title: You shouldn't see this as this file should be ignored!!!