openapi: 3.0.1
info:
  title: Your API
  version: 1.0.0
  license:
    name: MIT
    url: fakeurl
servers:
  - url: http://localhost:5601
    description: local
paths:
  /example:
    $ref: './paths/example.yaml'
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    NewSchema:
      type: object
      properties:
        email:
          type: string
        age:
          type: integer
      required:
        - email
security:
  - basicAuth: []
