# @kbn-doc-linker entry

openapi: 3.0.1
info:
  title: Your API
  version: 1.0.0
  license:
    name: "MIT"
    url: "fakeurl"
servers:
  - url: http://localhost:5601
    description: local
paths:
  /example:
    post:
      operationId: createExample
      summary: Create a new example
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/NewSchema"
                - $ref: "#/components/schemas/AnotherSchema"
      responses:
        "200":
          description: OK
        "400":
          description: KO
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    NewSchema:
      type: object
      properties:
        email:
          type: string
        age:
          type: integer
      required:
        - email
security:
  - basicAuth: []
